version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: "16.4.0"
      resource_class: m4pro.medium
    steps:
      - checkout
      - run: xcrun simctl list
      - run:
          name: Install build dependencies
          command: |
            sudo gem install xcpretty

      - run: make build-ios
      - run: make test-ios
      - run: make build-tvos
      - run: make test-tvos
      - run: make build-macos
      - run: make test-macos
      - run: make lint
      - run: make carthage

      - store_test_results:
          # relies on xcpretty --report junit
          path: build/reports
      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
  scheduled_e2e_test:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - main
                - scheduled_e2e_testing
    jobs:
      - build_and_test
